version: '3.0'
services:
  go-app:
    build: 
      context: .
      dockerfile: ./Dockerfile.redis
    networks:
      - my_network
    depends_on:
      - redis-db
    environment:
      - REDIS_HOST=redis-db
    ports:
      - 8080:8080

  redis-db:
    image: redis:latest
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
